-- Execute este script no SQL Editor do Supabase após auth-migration.sql.

create table if not exists public.materiais (
  id bigint generated by default as identity primary key,
  nome text not null check (length(trim(nome)) > 0),
  unidade text not null default 'un',
  preco_unitario numeric(12, 2) not null check (preco_unitario >= 0),
  quantidade_estoque numeric(12, 3) not null default 0 check (quantidade_estoque >= 0),
  created_at timestamptz not null default now()
);

create index if not exists materiais_nome_idx on public.materiais (nome);

alter table public.materiais enable row level security;

drop policy if exists "authenticated access to materiais" on public.materiais;
create policy "authenticated access to materiais" on public.materiais
for all to authenticated using (true) with check (true);

notify pgrst, 'reload schema';
