-- Execute este arquivo no SQL Editor do projeto Supabase.
-- O Mini ERP ainda não possui autenticação. As políticas abaixo permitem uso
-- anônimo apenas para demonstração; restrinja-as a usuários autenticados antes
-- de publicar o sistema.

create table if not exists public.produtos (
  id bigint generated by default as identity primary key,
  nome text not null check (length(trim(nome)) > 0),
  categoria text not null default '',
  preco numeric(12, 2) not null check (preco >= 0),
  quantidade integer not null default 0 check (quantidade >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.movimentacoes (
  id bigint generated by default as identity primary key,
  produto_id bigint references public.produtos(id) on delete set null,
  produto text not null,
  tipo text not null check (tipo in ('Entrada', 'Saída', 'Venda')),
  quantidade integer not null check (quantidade > 0),
  created_at timestamptz not null default now()
);

create table if not exists public.vendas (
  id bigint generated by default as identity primary key,
  produto_id bigint references public.produtos(id) on delete set null,
  produto text not null,
  quantidade integer not null check (quantidade > 0),
  valor numeric(12, 2) not null check (valor >= 0),
  created_at timestamptz not null default now()
);

create index if not exists movimentacoes_created_at_idx on public.movimentacoes (created_at desc);
create index if not exists vendas_created_at_idx on public.vendas (created_at desc);

alter table public.produtos enable row level security;
alter table public.movimentacoes enable row level security;
alter table public.vendas enable row level security;

create policy "demo public access to produtos" on public.produtos for all to anon, authenticated using (true) with check (true);
create policy "demo public access to movimentacoes" on public.movimentacoes for all to anon, authenticated using (true) with check (true);
create policy "demo public access to vendas" on public.vendas for all to anon, authenticated using (true) with check (true);

create or replace function public.registrar_movimentacao_estoque(
  p_produto_id bigint,
  p_tipo text,
  p_quantidade integer
)
returns void
language plpgsql
as $$
declare
  produto_atual public.produtos;
  nova_quantidade integer;
begin
  if p_tipo not in ('Entrada', 'Saída') or p_quantidade <= 0 then
    raise exception 'Movimentação inválida';
  end if;

  select * into produto_atual from public.produtos where id = p_produto_id for update;
  if not found then
    raise exception 'Produto não encontrado';
  end if;

  nova_quantidade := produto_atual.quantidade + case when p_tipo = 'Entrada' then p_quantidade else -p_quantidade end;
  if nova_quantidade < 0 then
    raise exception 'Estoque insuficiente';
  end if;

  update public.produtos set quantidade = nova_quantidade where id = p_produto_id;
  insert into public.movimentacoes (produto_id, produto, tipo, quantidade)
  values (produto_atual.id, produto_atual.nome, p_tipo, p_quantidade);
end;
$$;

create or replace function public.registrar_venda(
  p_produto_id bigint,
  p_quantidade integer
)
returns void
language plpgsql
as $$
declare
  produto_atual public.produtos;
begin
  if p_quantidade <= 0 then
    raise exception 'Quantidade inválida';
  end if;

  select * into produto_atual from public.produtos where id = p_produto_id for update;
  if not found then
    raise exception 'Produto não encontrado';
  end if;
  if produto_atual.quantidade < p_quantidade then
    raise exception 'Estoque insuficiente';
  end if;

  update public.produtos set quantidade = quantidade - p_quantidade where id = p_produto_id;
  insert into public.movimentacoes (produto_id, produto, tipo, quantidade)
  values (produto_atual.id, produto_atual.nome, 'Venda', p_quantidade);
  insert into public.vendas (produto_id, produto, quantidade, valor)
  values (produto_atual.id, produto_atual.nome, p_quantidade, produto_atual.preco * p_quantidade);
end;
$$;

grant execute on function public.registrar_movimentacao_estoque(bigint, text, integer) to anon, authenticated;
grant execute on function public.registrar_venda(bigint, integer) to anon, authenticated;
